//
//  File.swift
//  BugMe
//
//  Created by Abhijith Pm on 10/3/25.
//

import Foundation

class HTMLFooter: HTMLContent {
    let generatorName: String
    
    init(generatorName: String = "AppReport Mirror Inspector") {
        self.generatorName = generatorName
    }
    
    func html() -> String {
        return """
            <div class="footer">
                <p>Generated by \(generatorName)</p>
            </div>
        </body>
        </html>
        """
    }
}
